[package]
name = "shutdown"
version = "0.1.0"
authors = ["Sahil2004 <sahilgarg3920@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system_shutdown = "3.0.0"